In [4]:
import pandas as pd
import numpy as np
import os
os.chdir(os.pardir)

import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, column_property
from sqlalchemy.ext.hybrid import hybrid_method, hybrid_property
from sqlalchemy.pool import NullPool
from tycho.helper import SQLiteCon

In [5]:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~ SQLAlchemy Models ~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# --- Create Write Engine ---
dashboard_engine = sa.create_engine('sqlite:///data/sqlite/tycho_dashboard.sqlite')
# dashboard_engine = sa.create_engine("postgresql://tycho:tycho@dashboard.postgresql")

# --- Initialize SQLAlchemy Base ---
Base = declarative_base()

class Prediction(Base):
    """SQLAlchemy ORM Wrapper to individual predictions."""

    __tablename__ = 'prediction'

    pred_id = sa.Column(sa.Integer, primary_key=True)
    plant_id_wri = sa.Column(sa.String(12), sa.ForeignKey('plant.gppd_idnr'))
    timestamp = sa.Column(sa.DateTime)
    timestamp_year = sa.Column(sa.Integer)
    timestamp_month = sa.Column(sa.Integer)
    gross_load_mw = sa.Column(sa.Float)
    so2_lbs = sa.Column(sa.Float)
    nox_lbs = sa.Column(sa.Float)
    co2_lbs = sa.Column(sa.Float)

    def __repr__(self):
        return f"<Prediction {self.plant_id_wri}, {self.timestamp}, LOAD: {round(self.gross_load_mw,1)}, SO2: {round(self.so2_lbs,0)}, NOX: {round(self.nox_lbs, 1)}, CO2: {round(self.co2_lbs, 1)}>"


class Plant(Base):
    """SQLAlchemy ORM Wrapper to Plants."""

    __tablename__ = 'plant'

    # --- WRI Columns ---
    gppd_idnr = sa.Column(sa.String(12), primary_key=True)
    country = sa.Column(sa.String(3), sa.ForeignKey('country.iso3'))
    country_long = sa.Column(sa.String(50))
    name = sa.Column(sa.String(50))
    capacity_mw = sa.Column(sa.Float)
    latitude = sa.Column(sa.Float)
    longitude = sa.Column(sa.Float)
    primary_fuel = sa.Column(sa.String(12))
    other_fuel1 = sa.Column(sa.String(12))
    other_fuel2 = sa.Column(sa.String(12))
    other_fuel3 = sa.Column(sa.String(12))
    commissioning_year = sa.Column(sa.Integer)
    owner = sa.Column(sa.String(120))
    source = sa.Column(sa.String(120))
    url = sa.Column(sa.String(120))
    geolocation_source = sa.Column(sa.String(50))
    wepp_id = sa.Column(sa.Integer)
    year_of_capacity_data = sa.Column(sa.Integer)
    generation_gwh_2013 = sa.Column(sa.Float)
    generation_gwh_2014 = sa.Column(sa.Float)
    generation_gwh_2015 = sa.Column(sa.Float)
    generation_gwh_2016 = sa.Column(sa.Float)
    generation_gwh_2017 = sa.Column(sa.Float)
    estimated_generation_gwh = sa.Column(sa.Float)

    source = column_property(sa.func.substr(gppd_idnr, 1, 3).label('source'))

    co2_cum = column_property(sa.select([sa.func.sum(Prediction.co2_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('co2_cum'))
    nox_cum = column_property(sa.select([sa.func.sum(Prediction.nox_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('nox_cum'))
    so2_cum = column_property(sa.select([sa.func.sum(Prediction.so2_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('so2_cum'))

    @hybrid_method
    def emission_cum(self, emission):
        """Wrapper around co2_cum, nox_cum, and so2_cum to provide generalized function accepting name of emission as str."""
        if emission == 'co2': return self.co2_cum
        elif emission == 'nox': return self.nox_cum
        elif emission == 'so2': return self.so2_cum
    
    co2_avg = column_property(sa.select([sa.func.avg(Prediction.co2_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('co2_avg'))
    nox_avg = column_property(sa.select([sa.func.avg(Prediction.nox_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('nox_avg'))
    so2_avg = column_property(sa.select([sa.func.avg(Prediction.so2_lbs)]).where(Prediction.plant_id_wri==gppd_idnr).label('so2_avg'))

    @hybrid_method
    def emission_avg(self, emission):
        """Wrapper around co2_avg, nox_avg, and so2_avg to provide generalized function accepting name of emission as str."""
        if emission == 'co2': return self.co2_avg
        elif emission == 'nox': return self.nox_avg
        elif emission == 'so2': return self.so2_avg
    
    @hybrid_property
    def cf(self):
        return (self.estimated_generation_gwh * 1000) / (self.capacity_mw * 8760)

    def __repr__(self):
        return f'<Plant {self.plant_id_wri}, {self.iso3}, {self.primary_fuel} {self.capacity_mw} MW>'


class Country(Base):

    __tablename__ = 'country'

    id = sa.Column(sa.Integer, primary_key=True)
    iso3 = sa.Column(sa.String(3))
    plants = relationship('Plant', backref='country_name', lazy='joined')
    
    @hybrid_property
    def plant_ids(self):
        return [i[0] for i in session.query(Plant.gppd_idnr).filter(Plant.country == iso3).all()]

    n_plants = column_property(sa.select([sa.func.count(Plant.gppd_idnr)]).where(Plant.country == iso3).label('n_plants'))

    # @hybrid_method
    def dirtiest_plants(self, emission, n=10):
        query = session.query(Plant.gppd_idnr)\
                      .filter(Plant.country == iso3)\
                      .order_by(Plant.emission_cum(emission=emission).desc())\
                      .limit(n)
        return [i[0] for i in query.all()]
 
    co2_cum = column_property(sa.select([sa.func.sum(Plant.co2_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('co2_cum'))
    nox_cum = column_property(sa.select([sa.func.sum(Plant.nox_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('nox_cum'))
    so2_cum = column_property(sa.select([sa.func.sum(Plant.so2_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('so2_cum'))

    @hybrid_method
    def emission_cum(self, emission):
        """Wrapper around co2_cum, nox_cum, and so2_cum to provide generalized function accepting name of emission as str."""
        if emission == 'co2': return self.co2_cum
        elif emission == 'nox': return self.nox_cum
        elif emission == 'so2': return self.so2_cum

    co2_avg = column_property(sa.select([sa.func.avg(Plant.co2_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('co2_avg'))
    nox_avg = column_property(sa.select([sa.func.avg(Plant.nox_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('nox_avg'))
    so2_avg = column_property(sa.select([sa.func.avg(Plant.so2_cum)]).where(Plant.country==iso3).where(Plant.source == 'WRI').label('so2_avg'))

    @hybrid_method
    def emission_avg(self, emission):
        """Wrapper around co2_avg, nox_avg, and so2_avg to provide generalized function accepting name of emission as str."""
        if emission == 'co2': return self.co2_avg
        elif emission == 'nox': return self.nox_avg
        elif emission == 'so2': return self.so2_avg


    def __repr__(self):
        return f"<Country: {self.iso3}, # Plants: {len(self.n_plants)}>"

In [6]:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~ Convert output tables into Models ~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# --- Create Read Engine ---
sql_db = os.path.join('tycho_production.sqlite')
SQL = SQLiteCon(sql_db)
SQL.make_con()

# --- Read in Predictions from SQL to pandas ---
as_pandas = SQL.sql_to_pandas('predictions')

SQL.close_con()

# --- Create Tables in new database ---
Base.metadata.create_all(bind=dashboard_engine)

# --- subset predictions one entry per plant ---
unique_plants = as_pandas.drop_duplicates(subset='plant_id_wri')

# --- create write session ---
Session = sessionmaker(bind=dashboard_engine)
session = Session()

# --- Drop all rows from tables ---
session.query(Prediction).delete()
session.query(Plant).delete()
session.query(Country).delete()

# --- Load WRI database ---
wri = pd.read_csv(os.path.join('data','wri','global_power_plant_database.csv'))

# --- iteratively add plants to dashboard_sql ---
for index, row in unique_plants.iterrows():

    wri_data = wri.loc[wri['gppd_idnr'] == row['plant_id_wri']].to_dict('records')[0]
    
    plant = Plant(**wri_data)
    
    session.add(plant)
    session.commit()

# --- iterative add predictions to dashboard_sql ---
for index, row in as_pandas.iterrows():

    prediction = Prediction()
    prediction.plant_id_wri = row['plant_id_wri']
    prediction.timestamp = row['datetime_utc']
    prediction.timestamp_year = row['datetime_utc'].year
    prediction.timestamp_month = row['datetime_utc'].month
    prediction.gross_load_mw = row['pred_gross_load_mw']
    prediction.so2_lbs = row['pred_so2_lbs']
    prediction.nox_lbs = row['pred_nox_lbs']
    prediction.co2_lbs = row['pred_co2_lbs']

    session.add(prediction)
    session.commit()

for iso3 in as_pandas['country'].unique():
    country = Country()
    country.iso3 = iso3
    
    session.add(country)
    session.commit()

In [7]:
# --- test: get plants and emissions for map ---
emission = 'co2'
query = session.query(Plant.gppd_idnr,
                      Plant.name,
                      Plant.country,
                      Plant.cf,
                      Plant.longitude, Plant.latitude,
                      Plant.emission_cum(emission=emission).label(emission),
                      Plant.primary_fuel)\
                .filter(Plant.source == 'WRI')\
                .order_by(sa.desc(emission)).limit(20)
                
pd.read_sql(query.statement, dashboard_engine)

,gppd_idnr,name,country,cf,longitude,latitude,co2,primary_fuel
0,WRI1000160,Mae Mah,THA,0.815559,99.7499,18.2963,3.025089e+10,Coal
1,WRI1020064,Shinchi power station,JPN,0.959236,140.9456,37.8427,2.838233e+10,Coal
2,WRI1005616,Boxberg power station,DEU,0.680806,14.5619,51.4163,2.818832e+10,Coal
3,WRI1000618,Haramachi power station,JPN,0.959236,141.0165,37.6660,2.808408e+10,Coal
4,WRI1000669,J-POWER Tachibana-wan power station,JPN,0.959236,134.6514,33.8572,2.790699e+10,Coal
5,WRI1020046,Nakoso power station,JPN,0.959236,140.8128,36.9128,2.785434e+10,Coal
6,WRI1075821,Samcheok Green power station,KOR,0.797602,129.3418,37.1860,2.775624e+10,Coal
7,WRI1000635,Hitachinaka power station,JPN,0.959236,140.6138,36.4368,2.768819e+10,Coal
8,WRI1000652,Maizuru power station,JPN,0.959236,135.3420,35.5270,2.747407e+10,Coal
9,WRI1005906,Janschwalde power station,DEU,0.680806,14.4590,51.8344,2.682091e+10,Coal
10,WRI1000367,Hsinta (coal),TWN,1.008935,120.1972,22.8558,2.680302e+10,Coal
11,WRI1000187,Yeongheung,KOR,0.797602,126.4361,37.2369,2.656311e+10,Coal
12,WRI1000670,Matsuura power station,JPN,0.959236,129.6925,33.3552,2.643601e+10,Coal
13,WRI1000127,Kriel power station,ZAF,0.665585,29.1801,-26.2540,2.565530e+10,Coal
14,WRI1000616,Tomato-atsuma power station,JPN,0.959236,141.8050,42.6120,2.555701e+10,Coal
15,WRI1000362,Mailao,TWN,1.008935,120.1902,23.8033,2.506209e+10,Coal
16,WRI1008361,Orot Rabin,ISR,0.710782,34.8880,32.4700,2.425864e+10,Coal
17,WRI1000637,Hekinan power station,JPN,0.959236,136.9609,34.8352,2.397738e+10,Coal
18,WRI1000286,Ekibastuz-1 power station,KAZ,0.543827,75.3770,51.8880,2.350060e+10,Coal
19,WRI1075823,Shin Boryeong power station,KOR,0.797602,126.4862,36.3846,2.344783e+10,Coal

In [8]:
# --- test: get dirtiest plants for a country ---
country = 'VEN'
country_results = session.query(Country).filter(Country.iso3 == country)
for i in country_results:
    dirtiest_plants = i.dirtiest_plants(emission='co2', n=3)
    for index, plant_id in enumerate(dirtiest_plants):
        plant_results = session.query(Plant).filter(Plant.gppd_idnr == plant_id)
        for plant in plant_results:

            print(f"""
                    DIRTIEST PLANT #{index+1}: {plant_id}, 
                    MW: {plant.capacity_mw} CF: {round(plant.cf,3)*100}%
                    \n\t\t\tCO2 thousand tons: {round(plant.co2_cum/2000000, 1)} (cum) / {round(plant.co2_avg/2000000, 1)} (avg) 
                    \n\t\t\tNOX tons: {round(plant.nox_cum/2000, 1)} (cum) / {round(plant.nox_avg/2000, 1)} (avg)
                    \n\t\t\tSO2 tons: {round(plant.so2_cum/2000, 1)} (cum) / {round(plant.so2_avg/2000, 1)} (avg)\n """)

                    DIRTIEST PLANT #1: GEODB0040404,
                    MW: 920.0 CF: 54.6%

			CO2 thousand tons: 4289.4 (cum) / 82.5 (avg)

			NOX tons: 2157.1 (cum) / 41.5 (avg)

			SO2 tons: 1557.7 (cum) / 30.0 (avg)

In [9]:
# --- test: get annual emissions for 20 countries  ---
emission = 'co2'
query = session.query(Country.iso3,
                      Country.emission_cum(emission=emission),
                      Country.emission_avg(emission=emission),
                      Country.n_plants).limit(20)
                      
pd.read_sql(query.statement, dashboard_engine)

   iso3       co2_cum       co2_avg  n_plants
0   AFG           NaN           NaN         1
1   DZA  6.524128e+10  2.104557e+09        31
2   AGO  1.446347e+10  1.607052e+09         9
3   ATA  1.825169e+09  1.825169e+09         1
4   ARG           NaN           NaN       162
5   ARM  4.609083e+09  1.536361e+09         3
6   AUS           NaN           NaN       210
7   AUT  5.516206e+09  1.838735e+09         3
8   AZE  1.813535e+10  2.015039e+09         9
9   BHR  2.047530e+10  2.925043e+09         7
10  BGD  7.953379e+10  1.472848e+09        54
11  BLR           NaN           NaN        17
12  BEL  3.763052e+10  1.254351e+09        30
13  BEN  3.921511e+09  1.960756e+09         2
14  BOL           NaN           NaN         9
15  BIH           NaN           NaN         4
16  BWA  6.319696e+09  3.159848e+09         2
17  BRA           NaN           NaN       764
18  BRN           NaN           NaN         4
19  BGR  4.585421e+10  4.168565e+09        11